name: Filter issues
on:
  # Run manually
  workflow_dispatch:

jobs:
  filter_bugs:
    name: Filter bugs
    runs-on: ubuntu-latest
    steps:
      - id: filter_bugs
        uses: smockle/action-filter-issues@dist
        with:
          owner: smockle
          repo: action-filter-issues
          included_labels: '["bug"]'
          excluded_labels: '["wip"]'
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
      - run: echo ${{ steps.filter_bugs.outputs.issue_numbers }}
